### ISSUE TITLE
Add const

### ISSUE THREAD

**Issue by IanaKhitsko** [immaria/software_engineering#1]
https://github.com/immaria/software_engineering/blob/347c34f1076ba25cb7dbff2a8c805782f5e4e8f4/City.h#L41

1000 can be const

**Comment by immaria** [comment]
Fixed
https://github.com/immaria/software_engineering/blob/6b1bfbd2405fb51a7402dec9e5cfc2801f45718a/City.h#L8
https://github.com/immaria/software_engineering/blob/6b1bfbd2405fb51a7402dec9e5cfc2801f45718a/City.h#L39-L50
