### ISSUE TITLE
std::any

### ISSUE THREAD

**Issue by IanaKhitsko** [immaria/software_engineering#2]
https://github.com/immaria/software_engineering/blob/347c34f1076ba25cb7dbff2a8c805782f5e4e8f4/City.h#L71

Have you tried to use std::any_of ? (with lambda as predicate)

**Comment by immaria** [comment]
Fixed
https://github.com/immaria/software_engineering/blob/c8c7a5158bbbe05e704740cda149c42aa3680992/City.h#L69-L74
