### ISSUE TITLE
Use ranged for

### ISSUE THREAD

**Issue by IanaKhitsko** [immaria/software_engineering#3]
https://github.com/immaria/software_engineering/blob/347c34f1076ba25cb7dbff2a8c805782f5e4e8f4/City.h#L81

either use std::all_of here or at least ranged for ( for (auto& neibour: neighbours) {             if(neighbour->country != country)
                return true;} )

**Comment by immaria** [comment]
Fixed
https://github.com/immaria/software_engineering/blob/10c0a7a54b7372a9da75a20db03b9154f28a5c1b/City.h#L76-L82
