### ISSUE TITLE
Using all_of will make this method elegant

### ISSUE THREAD

**Issue by IanaKhitsko** [immaria/software_engineering#4]
https://github.com/immaria/software_engineering/blob/347c34f1076ba25cb7dbff2a8c805782f5e4e8f4/Country.h#L59

return std::all_of(cities.begin(), cities.end(), [](auto& city) { return city->is_has_all_coins_types(); })

Consider similar approach for other methods here

**Comment by immaria** [comment]
Fixed
https://github.com/immaria/software_engineering/blob/10c0a7a54b7372a9da75a20db03b9154f28a5c1b/Country.h#L57-L62
