### ISSUE TITLE
Can we add null country?

### ISSUE THREAD

**Issue by IanaKhitsko** [immaria/software_engineering#5]
https://github.com/immaria/software_engineering/blob/347c34f1076ba25cb7dbff2a8c805782f5e4e8f4/WorldMap.h#L28

Can we add country == nullptr here?

**Comment by immaria** [comment]
Fixed
https://github.com/immaria/software_engineering/blob/10c0a7a54b7372a9da75a20db03b9154f28a5c1b/WorldMap.h#L26-L32
