### ISSUE TITLE
10 can be const

### ISSUE THREAD

**Issue by IanaKhitsko** [immaria/software_engineering#6]
https://github.com/immaria/software_engineering/blob/347c34f1076ba25cb7dbff2a8c805782f5e4e8f4/WorldMapBuilder.h#L22

Subj

**Comment by immaria** [comment]
Fixed
https://github.com/immaria/software_engineering/blob/10c0a7a54b7372a9da75a20db03b9154f28a5c1b/WorldMapBuilder.h#L6-L7
https://github.com/immaria/software_engineering/blob/10c0a7a54b7372a9da75a20db03b9154f28a5c1b/WorldMapBuilder.h#L25
