### ISSUE TITLE
Catch?

### ISSUE THREAD

**Issue by IanaKhitsko** [immaria/software_engineering#7]
https://github.com/immaria/software_engineering/blob/347c34f1076ba25cb7dbff2a8c805782f5e4e8f4/WorldMapBuilder.h#L118

Who will catch the exception?

**Comment by immaria** [comment]
Catched in main.cpp
https://github.com/immaria/software_engineering/blob/10c0a7a54b7372a9da75a20db03b9154f28a5c1b/main.cpp#L44-L50
